compiler:
    solc:
        version: 0.8.15
        optimizer:
            enabled: true
            runs: 200
networks:
    default: celo-alfajores
console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs
dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
    from_mnemonic: ${MNEMONIC}